@include('frontend.templates.header')


<main>

    <!-- breadcrumb area start -->
    <section class="breadcrumb__area include-bg text-center pt-95 pb-50">
       <div class="container">
          <div class="row">
             <div class="col-xxl-12">
                <div class="breadcrumb__content p-relative z-index-1">
                   <h3 class="breadcrumb__title">Terms & conditions</h3>
                   <div class="breadcrumb__list">
                      <span><a href="{{ route('frontend.home')}}">Home</a></span>
                      <span>Terms & conditions</span>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </section>
    <!-- breadcrumb area end -->


    <section class="tp-postbox-area">
        <div class="container">
           <div class="row">
              <div class="col-xl-12 col-lg-8">
                 <div class="tp-postbox-wrapper pr-50">
                    <article class="tp-postbox-item format-image mb-50 transition-3">
                       <div class="tp-postbox-content">
                          <p class="tp-postbox-title" style="font-size: 20px">
                             <!-- <a href="blog-details.html"> <b>TERMS & CONDITIONS</b> </a> -->
                          </p>
                          <div class="tp-postbox-text">
                             <p>
<b>O</b>ur Terms and Conditions were last updated on September 23, 2023. Please read these terms and conditions carefully before using Our Service.<br>
<b>Interpretation and Definitions :</b><br><br>
<b>Interpretation</b><br>
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.<br><br>
<b>Definitions</b><br>
For these Terms and Conditions:
“Affiliate” means an entity that controls, is controlled by, or is under common control with a party, whereas “control” means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.
“Account” means a unique account created for You to access our Service or parts of our Service.
“Company” (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Spiciffy.com.
“Country” refers to India.<br>
“Content” refers to content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content.<br>
“Device” means any device that can access the Service such as a computer, a cellphone, or a digital tablet.
“Feedback” means feedback, innovations, or suggestions sent by You regarding the attributes, performance, or features of our Service.
“Products” refer to the products or items offered for sale on the Service.
“Orders” means a request by You to purchase Products from Us.
“Promotions” refer to contests, sweepstakes, or other promotions offered through the Service.
“Service” refers to the Website.<br>
“Terms and Conditions” (also referred to as “Terms“) mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated by the TermsFeed Terms and Conditions Generator.
“Third-party Social Media Service” means any services or content (including data, information, products, or services) provided by a third party that may be displayed, included, or made available by the Service.<br>
“Website” refers to Spiciffy.com, accessible from https://Spiciffy.com/<br>
“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.<br><br><b>
Acknowledgment</b><br>
These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.
Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users, and others who access or use the Service.<br>
By accessing or using the service you agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.<br>
You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.<br>
Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects you. Please read Our Privacy Policy carefully before using Our Service.
User Accounts<br>
When You create an account with Us, You must provide Us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of Your account on Our Service.
You are responsible for safeguarding the password that You use to access the Service and for any activities or actions under Your password, whether Your password is with Our Service or a Third-Party Social Media Service.<br>
You agree not to disclose Your password to any third party. You must notify Us immediately upon becoming aware of any breach of security or unauthorized use of Your account.<br>
You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than You without appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.
Content<br>
Your Right to Post Content<br>
Our Service allows You to post Content. You are responsible for the Content that You post to the Service, including its legality, reliability, and appropriateness.<br>
By posting Content to the Service, You grant Us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. You retain any of Your rights to any Content You submit, post, or display on or through the Service and You are responsible for protecting those rights. You agree that this license includes the right for Us to make Your Content available to other users of the Service, who may also use Your Content subject to these Terms.<br>
You represent and warrant that: (i) the Content is Yours (You own it) or You have the right to use it and grant Us the rights and license as provided in these Terms, and (ii) the posting of Your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person.<br><br>
<b>Content Restrictions</b><br>
The Company is not responsible for the content of the Service’s users. You expressly understand and agree that You are solely responsible for the Content and for all activity that occurs under your account, whether done so by You or any third person using Your account.
You may not transmit any Content that is unlawful, offensive, upsetting, intended to disgust, threatening, libelous, defamatory, obscene, or otherwise objectionable. Examples of such objectionable Content include, but are not limited to, the following:
Unlawful or promoting unlawful activity.
Defamatory, discriminatory, or mean-spirited content, including references or commentary about religion, race, sexual orientation, gender, national/ethnic origin, or other targeted groups.<br>
Spam, machine – or randomly–generated, constituting unauthorized or unsolicited advertising, chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling.<br>
Containing or installing any viruses, worms, malware, trojan horses, or other content that is designed or intended to disrupt, damage, or limit the functioning of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any data or other information of a third person.<br>
Infringing on any proprietary rights of any party, including patent, trademark, trade secret, copyright, right of publicity, or other rights.
Impersonating any person or entity including the Company and its employees or representatives.<br>
Violating the privacy of any third person.<br><br>
<b>False information and features.</b><br>
The Company reserves the right, but not the obligation, to, in its sole discretion, determine whether or not any Content is appropriate and complies with these Terms, refuse or remove this Content. The Company further reserves the right to make formatting and edits and change the manner of any Content. The Company can also limit or revoke the use of the Service if You post such objectionable Content. As the Company cannot control all content posted by users and/or third parties on the Service, you agree to use the Service at your own risk. You understand that by using the Service You may be exposed to content that You may find offensive, indecent, incorrect, or objectionable, and You agree that under no circumstances will the Company be liable in any way for any content, including any errors or omissions in any content, or any loss or damage of any kind incurred as a result of your use of any content.<br><br>
<b>Content Backups</b><br>
Although regular backups of Content are performed, the Company does not guarantee there will be no loss or corruption of data.
Corrupt or invalid backup points may be caused by, without limitation, Content that is corrupted before being backed up or that changes during the time a backup is performed.<br>
The Company will provide support and attempt to troubleshoot any known or discovered issues that may affect the backups of Content. But You acknowledge that the Company has no liability related to the integrity of Content or the failure to successfully restore Content to a usable state.<br>
You agree to maintain a complete and accurate copy of any Content in a location independent of the Service.<br><br>
<b>Copyright Policy</b><br>
Intellectual Property Infringement
We respect the intellectual property rights of others. It is Our policy to respond to any claim that Content posted on the Service infringes a copyright or other intellectual property infringement of any person.<br>
If You are a copyright owner, or authorized on behalf of one, and You believe that the copyrighted work has been copied in a way that constitutes copyright infringement that is taking place through the Service, you must submit Your notice in writing to the attention of our copyright agent via email support@spiciffy.com and include in Your notice a detailed description of the alleged infringement.<br>
You may be held accountable for damages (including costs and attorneys’ fees) for misrepresenting that any Content is infringing Your copyright.
DMCA Notice and DMCA Procedure for Copyright Infringement Claims<br>
You may submit a notification under the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):<br>
An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright’s interest.
A description of the copyrighted work that You claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work.<br>
Identification of the URL or other specific location on the Service where the material that You claim is infringing is located.
Your address, telephone number, and email address.<br>
A statement by You that You have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.
A statement by You, made under penalty of perjury, that the above information in Your notice is accurate and that You are the copyright owner or authorized to act on the copyright owner’s behalf.<br>
You can contact our copyright agent via email at support@spiciffy.com. Upon receipt of a notification, the Company will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged content from the Service.
Placing Orders for Products<br>
By placing an Order for Products through the Service, You warrant that You are legally capable of entering into binding contracts.<br><br>
<b>Your Information</b><br>
If You wish to place an Order for Products available on the Service, You may be asked to supply certain information relevant to Your Order including, without limitation, Your name, Your email, Your phone number, Your credit card number, the expiration date of Your credit card, UPI, Your billing address, and Your shipping information.<br>
You represent and warrant that: (i) You have the legal right to use any credit or debit card(s) or other payment method(s) in connection with any Order; and that (ii) the information You supply to us is true, correct and complete.<br>
By submitting such information, You grant us the right to provide the information to payment processing third parties for purposes of facilitating the completion of Your Order.<br><br><b>
Order Cancellation<br></b>
We reserve the right to refuse or cancel Your Order at any time for certain reasons including but not limited to:<br>
Products availability<br>
Errors in the description or prices of Products<br>
Errors in Your Order<br>
We reserve the right to refuse or cancel Your Order if fraud or an unauthorized or illegal transaction is suspected.<br>
Your Order Cancellation Rights
Any Products you purchase can only be returned or refunded by these Terms and Conditions.<br>
Availability, Errors, and Inaccuracies
We are constantly updating Our offerings of Products on the Service. The Products available on Our Service may be mispriced, described inaccurately, or unavailable, and We may experience delays in updating information regarding our Products on the Service and in Our advertising on other websites.
We cannot and do not guarantee the accuracy or completeness of any information, including prices, product images, specifications, availability, and services. We reserve the right to change or update information and to correct errors, inaccuracies, or omissions at any time without prior notice.<br><br>
<b>Prices Policy</b> <br>
The Company reserves the right to revise its prices at any time before accepting an Order.
The prices quoted may be revised by the Company after accepting an Order in the event of any occurrence affecting delivery caused by government action, variation in customs duties, increased shipping charges, higher foreign exchange costs, and any other matter beyond the control of the Company. In that event, You will have the right to cancel Your Order.<br><br>

<b>Payments</b><br>
Payment can be made through various payment methods we have available, such as Visa, MasterCard, or online payment methods (Paytm, GPay for example).
Payment cards (credit cards or debit cards) are subject to validation checks and authorization by Your card issuer. If we do not receive the required authorization, We will not be liable for any delay or non-delivery of Your Order.<br><br>
<b>Promotions</b><br>
Any Promotions made available through the Service may be governed by rules that are separate from these Terms.
If You participate in any Promotions, please review the applicable rules as well as our Privacy policy. If the rules for a Promotion conflict with these Terms, the Promotion rules will apply.<br><br><b>
Intellectual Property</b><br>
The Service and its original content (excluding Content provided by You or other users), features, and functionality are and will remain the exclusive property of the Company and its licensors.<br>
The Service is protected by copyright, trademark, and other laws of India.<br>
Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of the Company.
Your Feedback to Us
You assign all rights, title, and interest in any Feedback You provide the Company. If for any reason such assignment is ineffective, You agree to grant the Company a non-exclusive, perpetual, irrevocable, royalty-free, worldwide right and license to use, reproduce, disclose, sub-license, distribute, modify, and exploit such Feedback without restriction.
Links to Other Websites
Our Service may contain links to third-party websites or services that are not owned or controlled by the Company.
The Company has no control over and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such web sites or services.<br>
We strongly advise You to read the terms and conditions and privacy policies of any third-party websites or services that You visit.
Termination<br>
We may terminate or suspend Your Account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.<br>
Upon termination, Your right to use the Service will cease immediately. If You wish to terminate Your Account, You may simply discontinue using the Service.<br><br>
<b>Limitation of Liability</b><br>
Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount paid by You through the payment website.
To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.
Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party’s liability will be limited to the greatest extent permitted by law.<br><br>
<b>“AS IS”</b> and <b>“AS AVAILABLE” Disclaimer</b><br>
The Service is provided to You “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its behalf and behalf of its Affiliates and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory, or otherwise, concerning the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems, or services, operate without interruption, meet any performance or reliability standards or be error-free or that any errors or defects can or will be corrected.
Without limiting the foregoing, neither the Company nor any of the Company’s providers make any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan, worms, malware, or other harmful components.<br>
Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations outlined in this section shall be applied to the greatest extent enforceable under applicable law.<br><br>
<b>Governing Law</b><br>
The laws of the Country, excluding its conflicts of law rules, shall govern these Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.<br><br><b>
Disputes Resolution</b><br>
If You have any concerns or disputes about the Service, You agree to first try to resolve the dispute informally by contacting the Company.
Severability and Waiver<br><br>
<b>Severability</b><br>
If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.<br><br>
<b> Waiver</b><br>
Except as provided herein, the failure to exercise a right or to require the performance of an obligation under this Terms shall not affect a party’s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute a waiver of any subsequent breach.<br><br>
 
<b>Changes to These Terms and Conditions</b> <br>
We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at Our sole discretion.<br>
 By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.<br>
Contact Us
If you have any questions about these Terms and Conditions, You can contact us:
By sending us an email: support@spiciffy.com</p>
                          </div>

                       </div>
                    </article>

                 </div>
              </div>



            

           </div>
        </div>
     </section>

 </main>


@include('frontend.templates.footer')
